# Generated by Django 3.1.5 on 2021-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210115_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
