# Generated by Django 3.1.5 on 2021-01-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_comment_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='like',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
